from .usuario import Usuario as UsuarioResources
from .usuario import Usuarios as UsuariosResources
from .libro import Libro as LibroResources
from .libro import Libros as LibrosResources
from .prestamos import Prestamo as PrestamoResources
from .prestamos import Prestamos as PrestamosResources
from .notificacion import Notificacion as NotificacionResources
from .sign_in import sign_in as SigninResources
#from .sign_in import log_in as LoginResources
from .valoracion import Resena as ResenaResources
from .valoracion import Resenas as ResenasResources
from .autor import Autor as AutorResources
from .autor import Autores as AutoresResources